### ISSUE TITLE
NRF52840_DK: GAP Example: Compiling failed

### ISSUE THREAD

**Issue by soramame21** [ARMmbed/mbed-os-example-ble#202]
I got a compilation error for NRF52840_DK with following steps.

```
C:\ioT\511ooB\rc2\mbed-os-example-ble-GAP>git log
commit 5c195e696412bd679dac7c70d7fed9a8d07f5a85 (HEAD -> mbed-os-5.11.0-oob, origin/mbed-os-5.11.0-oob, origin/HEAD)
Author: Marcelo Salazar <marcelo.salazar@arm.com>
Date:   Thu Dec 6 14:43:15 2018 +0000

    Update BLE GAP app to 5.11-RC2

commit 5ec24c130e1a8b51a70e8b27e7308c4cda20ff97
Author: Marcelo Salazar <marcelo.salazar@arm.com>
Date:   Mon Dec 3 12:37:30 2018 +0000

    Update BLE GAP app to 5.11-RC1

C:\ioT\511ooB\rc2\mbed-os-example-ble-GAP>mbed compile -m NRF52840_DK -t ARM -vv -f
;;;
[DEBUG] Output: .\mbed-os\targets\TARGET_NORDIC\TARGET_NRF5x\us_ticker.c: 3 warnings, 0 errors
Compile [100.0%]: main.cpp
Compile: C:\Keil_v5\ARM\ARMCC\bin\armcc -c --gnu -Otime --split_sections --apcs=interwork --brief_diagnostics --restrict --multibyte_chars -O3 --cpu=Cortex-M4.fp --md --no_depend_system_headers --c99 -D__ASSERT_MSG --cpp --no_rtti --no_vla -DMBED_ROM_START=0x0 -DMBED_ROM_SIZE=0x100000 -DMBED_RAM_START=0x20000000 -DMBED_RAM_SIZE=0x40000 -DFEATURE_CRYPTOCELL310=1 -DCMSIS_VECTAB_VIRTUAL -D__MBED__=1 -DDEVICE_SYSTICK_CLK_OFF_DURING_SLEEP=1 -D__FPU_PRESENT=1 -DDEVICE_PORTINOUT=1 -DTARGET_RTOS_M4_M7 -DDEVICE_MPU=1 -DDEVICE_SERIAL_ASYNCH=1 -D__CMSIS_RTOS -DDEVICE_ITM=1 -DTARGET_SOFTDEVICE_NONE -DMBEDTLS_CONFIG_HW_SUPPORT -DNRF52840_XXAA -DDEVICE_USTICKER=1 -DWSF_MAX_HANDLERS=10 -DTARGET_NRF52840_DK -DTARGET_NORDIC_CORDIO -DTARGET_CORTEX_M -DDEVICE_I2C_ASYNCH=1 -DTARGET_LIKE_CORTEX_M4 -DDEVICE_TRNG=1 -DTARGET_M4 -DDEVICE_QSPI=1 -DFEATURE_BLE=1 -DCOMPONENT_PSA_SRV_IMPL=1 -DDEVICE_SPI_ASYNCH=1 -DDEVICE_LPTICKER=1 -DDEVICE_PWMOUT=1 -DTARGET_NRF5x -DMBED_TICKLESS -DDEVICE_INTERRUPTIN=1 -DTARGET_CORTEX -DDEVICE_I2C=1 -DDEVICE_PORTOUT=1 -D__CORTEX_M4 -DTARGET_LIKE_MBED -DCOMPONENT_PSA_SRV_EMUL=1 -DTARGET_FF_ARDUINO -DDEVICE_PORTIN=1 -DTARGET_RELEASE -DTARGET_SDK_14_2 -DTARGET_CORDIO -DTARGET_NORDIC -DTARGET_CORDIO_LL -DDEVICE_SERIAL_FC=1 -DCONFIG_GPIO_AS_PINRESET -DBOARD_PCA10056 -D__MBED_CMSIS_RTOS_CM -DDEVICE_SLEEP=1 -DMBED_BUILD_TIMESTAMP=1544585561.16 -DNRF52_ERRATA_20 -DDEVICE_SPI=1 -DCOMPONENT_NSPE=1 -DCMSIS_VECTAB_VIRTUAL_HEADER_FILE="cmsis_nvic.h" -DTOOLCHAIN_ARM_STD -DTARGET_MCU_NRF52840 -DDEVICE_ANALOGIN=1 -DDEVICE_SERIAL=1 -DTARGET_NRF52840 -DDEVICE_FLASH=1 -DTOOLCHAIN_ARM -DARM_MATH_CM4 -DTARGET_NRF52 --preinclude=.\BUILD\NRF52840_DK\ARM\mbed_config.h --via .\BUILD\NRF52840_DK\ARM\.includes_79773019d3251acc58ba13de3c0d29bb.txt --depend BUILD\NRF52840_DK\ARM\source\main.d -o BUILD\NRF52840_DK\ARM\source\main.o .\source\main.cpp
[Error] main.cpp@516,0:  #135: namespace "ble"  has no member "DisconnectionEvent"
[Warning] main.cpp@516,0:  #997-D: function "ble::Gap::EventHandler::onDisconnectionComplete(const ble::DisconnectionCompleteEvent &)"  is hidden by "GapDemo::onDisconnectionComplete"  -- virtual function override intended?
[Error] main.cpp@376,0:  #415: no suitable constructor exists to convert from "ble::duplicates_filter_t::type" to "ble::Duration<std::uint16_t, 10000U, ble::Range<0U, 65535U>, ble::Value<std::uint16_t, (std::uint16_t)0U>>"
[Error] main.cpp@377,0:  #312: no suitable user-defined conversion from "const ble::scan_duration_t" to "ble::duplicates_filter_t" exists
[Error] main.cpp@438,0:  #135: class "ble::AdvertisingReportEvent"  has no member "getAdvertisingData"
[Warning] main.cpp@761,0:  #111-D: statement is unreachable
[Warning] Duration.h@237,0:  #186-D: pointless comparison of unsigned integer with zero
[Warning] Bounded.h@47,0:  #186-D: pointless comparison of unsigned integer with zero
[Warning] Duration.h@237,0:  #186-D: pointless comparison of unsigned integer with zero
[Warning] Duration.h@237,0:  #186-D: pointless comparison of unsigned integer with zero
[Warning] Duration.h@237,0:  #186-D: pointless comparison of unsigned integer with zero
[DEBUG] Return: 1
[DEBUG] Output: ".\source\main.cpp", line 516: Error:  #135: namespace "ble"  has no member "DisconnectionEvent"
[DEBUG] Output: ".\source\main.cpp", line 516: Warning:  #997-D: function "ble::Gap::EventHandler::onDisconnectionComplete(const ble::DisconnectionCompleteEvent &)"  is hidden by "GapDemo::onDisconnectionComplete"  -- virtual function override intended?
[DEBUG] Output: ".\source\main.cpp", line 376: Error:  #415: no suitable constructor exists to convert from "ble::duplicates_filter_t::type" to "ble::Duration<std::uint16_t, 10000U, ble::Range<0U, 65535U>, ble::Value<std::uint16_t, (std::uint16_t)0U>>"
[DEBUG] Output: ".\source\main.cpp", line 377: Error:  #312: no suitable user-defined conversion from "const ble::scan_duration_t" to "ble::duplicates_filter_t" exists
[DEBUG] Output: ".\source\main.cpp", line 438: Error:  #135: class "ble::AdvertisingReportEvent"  has no member "getAdvertisingData"
[DEBUG] Output: ".\source\main.cpp", line 761: Warning:  #111-D: statement is unreachable
[DEBUG] Output: "./mbed-os/features/FEATURE_BLE/ble/common/Duration.h", line 237: Warning:  #186-D: pointless comparison of unsigned integer with zero
[DEBUG] Output:           detected during:
[DEBUG] Output:             instantiation of "Rep ble::Duration<Rep, TB, Range, Forever>::clamp(Rep) [with Rep=std::uint32_t, TB=1000U, Range=ble::Range<0U, 4294967295U>, Forever=void *]"  at line 120
[DEBUG] Output:             instantiation of "ble::Duration<Rep, TB, Range, Forever>::Duration(Rep) [with Rep=std::uint32_t, TB=1000U, Range=ble::Range<0U, 4294967295U>, Forever=void *]"  at line 657 of ".\source\main.cpp"
[DEBUG] Output: "./mbed-os/features/FEATURE_BLE/ble/common/Bounded.h", line 47: Warning:  #186-D: pointless comparison of unsigned integer with zero
[DEBUG] Output:           detected during instantiation of "ble::Bounded<Rep, Min, Max>::Bounded(Rep) [with Rep=std::uint16_t, Min=(std::uint16_t)0U, Max=(std::uint16_t)499U]"  at line 150 of "./mbed-os/features/FEATURE_BLE/ble/gap/ConnectionParameters.h"
[DEBUG] Output: "./mbed-os/features/FEATURE_BLE/ble/common/Duration.h", line 237: Warning:  #186-D: pointless comparison of unsigned integer with zero
[DEBUG] Output:           detected during:
[DEBUG] Output:             instantiation of "Rep ble::Duration<Rep, TB, Range, Forever>::clamp(Rep) [with Rep=std::uint16_t, TB=625U, Range=ble::Range<0U, 65535U>, Forever=void *]"  at line 120
[DEBUG] Output:             instantiation of "ble::Duration<Rep, TB, Range, Forever>::Duration(Rep) [with Rep=std::uint16_t, TB=625U, Range=ble::Range<0U, 65535U>, Forever=void *]"  at line 202
[DEBUG] Output:             instantiation of "ble::Duration<Rep, TB, Range, Forever> ble::Duration<Rep, TB, Range, Forever>::min() [with Rep=std::uint16_t, TB=625U, Range=ble::Range<0U, 65535U>, Forever=void *]"  at line 152 of "./mbed-os/features/FEATURE_BLE/ble/gap/ConnectionParameters.h"
[DEBUG] Output: "./mbed-os/features/FEATURE_BLE/ble/common/Duration.h", line 237: Warning:  #186-D: pointless comparison of unsigned integer with zero
[DEBUG] Output:           detected during:
[DEBUG] Output:             instantiation of "Rep ble::Duration<Rep, TB, Range, Forever>::clamp(Rep) [with Rep=std::uint16_t, TB=10000U, Range=ble::Range<0U, 65535U>, Forever=ble::Value<std::uint16_t, (std::uint16_t)0U>]"  at line 120
[DEBUG] Output:             instantiation of "ble::Duration<Rep, TB, Range, Forever>::Duration(Rep) [with Rep=std::uint16_t, TB=10000U, Range=ble::Range<0U, 65535U>, Forever=ble::Value<std::uint16_t, (std::uint16_t)0U>]"  at line 81 of ".\source\main.cpp"
[DEBUG] Output: "./mbed-os/features/FEATURE_BLE/ble/common/Duration.h", line 237: Warning:  #186-D: pointless comparison of unsigned integer with zero
[DEBUG] Output:           detected during:
[DEBUG] Output:             instantiation of "Rep ble::Duration<Rep, TB, Range, Forever>::clamp(Rep) [with Rep=std::uint16_t, TB=1280000U, Range=ble::Range<0U, 65535U>, Forever=void *]"  at line 120
[DEBUG] Output:             instantiation of "ble::Duration<Rep, TB, Range, Forever>::Duration(Rep) [with Rep=std::uint16_t, TB=1280000U, Range=ble::Range<0U, 65535U>, Forever=void *]"  at line 731 of "./mbed-os/features/FEATURE_BLE/ble/gap/Gap.h"
[DEBUG] Output: .\source\main.cpp: 7 warnings, 4 errors
Traceback (most recent call last):
  File "C:\ioT\511ooB\rc2\mbed-os-example-ble-GAP\mbed-os\tools\make.py", line 73, in wrapped_build_project
    src_dir, build_dir, mcu, *args, **kwargs
  File "C:\ioT\511ooB\rc2\mbed-os-example-ble-GAP\mbed-os\tools\build_api.py", line 540, in build_project
    objects = toolchain.compile_sources(resources, sorted(resources.get_file_paths(FileType.INC_DIR)))
  File "C:\ioT\511ooB\rc2\mbed-os-example-ble-GAP\mbed-os\tools\toolchains\__init__.py", line 413, in compile_sources
    return self.compile_queue(queue, objects)
  File "C:\ioT\511ooB\rc2\mbed-os-example-ble-GAP\mbed-os\tools\toolchains\__init__.py", line 476, in compile_queue
    raise ToolException(err)
ToolException: ".\source\main.cpp", line 516: Error:  #135: namespace "ble"  has no member "DisconnectionEvent"
".\source\main.cpp", line 516: Warning:  #997-D: function "ble::Gap::EventHandler::onDisconnectionComplete(const ble::DisconnectionCompleteEvent &)"  is hidden by "GapDemo::onDisconnectionComplete"  -- virtual function override intended?
".\source\main.cpp", line 376: Error:  #415: no suitable constructor exists to convert from "ble::duplicates_filter_t::type" to "ble::Duration<std::uint16_t, 10000U, ble::Range<0U, 65535U>, ble::Value<std::uint16_t, (std::uint16_t)0U>>"
".\source\main.cpp", line 377: Error:  #312: no suitable user-defined conversion from "const ble::scan_duration_t" to "ble::duplicates_filter_t" exists
".\source\main.cpp", line 438: Error:  #135: class "ble::AdvertisingReportEvent"  has no member "getAdvertisingData"
".\source\main.cpp", line 761: Warning:  #111-D: statement is unreachable
"./mbed-os/features/FEATURE_BLE/ble/common/Duration.h", line 237: Warning:  #186-D: pointless comparison of unsigned integer with zero
          detected during:
            instantiation of "Rep ble::Duration<Rep, TB, Range, Forever>::clamp(Rep) [with Rep=std::uint32_t, TB=1000U, Range=ble::Range<0U, 4294967295U>, Forever=void *]"  at line 120
            instantiation of "ble::Duration<Rep, TB, Range, Forever>::Duration(Rep) [with Rep=std::uint32_t, TB=1000U, Range=ble::Range<0U, 4294967295U>, Forever=void *]"  at line 657 of ".\source\main.cpp"
"./mbed-os/features/FEATURE_BLE/ble/common/Bounded.h", line 47: Warning:  #186-D: pointless comparison of unsigned integer with zero
          detected during instantiation of "ble::Bounded<Rep, Min, Max>::Bounded(Rep) [with Rep=std::uint16_t, Min=(std::uint16_t)0U, Max=(std::uint16_t)499U]"  at line 150 of "./mbed-os/features/FEATURE_BLE/ble/gap/ConnectionParameters.h"
"./mbed-os/features/FEATURE_BLE/ble/common/Duration.h", line 237: Warning:  #186-D: pointless comparison of unsigned integer with zero
          detected during:
            instantiation of "Rep ble::Duration<Rep, TB, Range, Forever>::clamp(Rep) [with Rep=std::uint16_t, TB=625U, Range=ble::Range<0U, 65535U>, Forever=void *]"  at line 120
            instantiation of "ble::Duration<Rep, TB, Range, Forever>::Duration(Rep) [with Rep=std::uint16_t, TB=625U, Range=ble::Range<0U, 65535U>, Forever=void *]"  at line 202
            instantiation of "ble::Duration<Rep, TB, Range, Forever> ble::Duration<Rep, TB, Range, Forever>::min() [with Rep=std::uint16_t, TB=625U, Range=ble::Range<0U, 65535U>, Forever=void *]"  at line 152 of "./mbed-os/features/FEATURE_BLE/ble/gap/ConnectionParameters.h"
"./mbed-os/features/FEATURE_BLE/ble/common/Duration.h", line 237: Warning:  #186-D: pointless comparison of unsigned integer with zero
          detected during:
            instantiation of "Rep ble::Duration<Rep, TB, Range, Forever>::clamp(Rep) [with Rep=std::uint16_t, TB=10000U, Range=ble::Range<0U, 65535U>, Forever=ble::Value<std::uint16_t, (std::uint16_t)0U>]"  at line 120
            instantiation of "ble::Duration<Rep, TB, Range, Forever>::Duration(Rep) [with Rep=std::uint16_t, TB=10000U, Range=ble::Range<0U, 65535U>, Forever=ble::Value<std::uint16_t, (std::uint16_t)0U>]"  at line 81 of ".\source\main.cpp"
"./mbed-os/features/FEATURE_BLE/ble/common/Duration.h", line 237: Warning:  #186-D: pointless comparison of unsigned integer with zero
          detected during:
            instantiation of "Rep ble::Duration<Rep, TB, Range, Forever>::clamp(Rep) [with Rep=std::uint16_t, TB=1280000U, Range=ble::Range<0U, 65535U>, Forever=void *]"  at line 120
            instantiation of "ble::Duration<Rep, TB, Range, Forever>::Duration(Rep) [with Rep=std::uint16_t, TB=1280000U, Range=ble::Range<0U, 65535U>, Forever=void *]"  at line 731 of "./mbed-os/features/FEATURE_BLE/ble/gap/Gap.h"
.\source\main.cpp: 7 warnings, 4 errors

[mbed] ERROR: "C:\Python27\python.exe" returned error.
       Code: 1
       Path: "C:\ioT\511ooB\rc2\mbed-os-example-ble-GAP"
       Command: "C:\Python27\python.exe -u C:\ioT\511ooB\rc2\mbed-os-example-ble-GAP\mbed-os\tools\make.py -t ARM -m NRF52840_DK --source . --build .\BUILD\NRF52840_DK\ARM -v"
       Tip: You could retry the last command with "-v" flag for verbose output
---
```

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBOCUSTRIA-304*

**Comment by pan-** [comment]
same issue as #201
